# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dd225cb00346dea75dc61634781cffaadf0eb9ee73eee5e43a4bef25c1c55721391fc162aaaaa45a3b4f1fbe894ad042cc2ab4c5c64a066b9134e3c3ddf00ef

test:
  secret_key_base: 74f5b8d5e775c5de1245d83ca90d9a3ff62ebdd4db474f559d249b29ccb1bf29eaa9a904dece7d9a69c77c72b95a94dd3dd13487be9108752ef2defcecc948cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
